apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: kafka
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
