apiVersion: v1
kind: Secret
metadata:
  name: kafka-ssl-secrets
  namespace: kafka
type: Opaque
data:
  # These are placeholders - in a real environment, you would generate actual keystores and truststores
  # and base64 encode them
  kafka.keystore.jks: ${BASE64_KEYSTORE}
  kafka.truststore.jks: ${BASE64_TRUSTSTORE}
  ssl-config.properties: |
    security.protocol=SSL
    ssl.keystore.location=/etc/kafka/ssl/kafka.keystore.jks
    ssl.keystore.password=${KEYSTORE_PASSWORD}
    ssl.key.password=${KEY_PASSWORD}
    ssl.truststore.location=/etc/kafka/ssl/kafka.truststore.jks
    ssl.truststore.password=${TRUSTSTORE_PASSWORD}
    ssl.client.auth=required
