apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: kafka
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: confluentinc/cp-kafka:7.3.2
        command:
        - /bin/bash
        - -c
        - |
          # Wait for Kafka to be ready
          echo "Waiting for Kafka to be ready..."
          sleep 30

          # Create the posts topic with 6 partitions and replication factor of 1
          kafka-topics --create --if-not-exists \
            --bootstrap-server kafka-service:9092 \
            --topic posts \
            --partitions 6 \
            --replication-factor 1 \
            --config retention.ms=604800000 \
            --config segment.bytes=1073741824 \
            --config cleanup.policy=delete \
            --config max.message.bytes=1000000

          echo "Topic 'posts' created successfully"
      restartPolicy: Never
  backoffLimit: 3
