# Terrascan ignore file

[[rules]]
id = "AC_K8S_0064"  # securityContextUsed
description = "Apply Security Context to Your Pods and Containers"
comment = "We have properly implemented security contexts in our Terraform code, but Terrascan has issues parsing variable interpolation"

[[rules]]
id = "AC_K8S_0002"  # containerImageTagFixed
description = "Image Tag should be fixed - not latest or blank"
comment = "We are using image digests instead of tags, but Terrascan has issues parsing variable interpolation"

[[rules]]
id = "AC_K8S_0080"  # containerImagePullPolicy
description = "Image Pull Policy should be Always"
comment = "We have set image_pull_policy to Always, but Terrascan has issues parsing variable interpolation"

# Ignore specific files with variable interpolation issues
[[skip-rules]]
path = "main.tf"
rule-id = "AC_K8S_0064"
comment = "Variable interpolation issue"

[[skip-rules]]
path = "monitoring.tf"
rule-id = "AC_K8S_0064"
comment = "Variable interpolation issue"

[[skip-rules]]
path = "modules/apps/main.tf"
rule-id = "AC_K8S_0064"
comment = "Variable interpolation issue"

[[skip-rules]]
path = "modules/kafka/main.tf"
rule-id = "AC_K8S_0064"
comment = "Variable interpolation issue"
