global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- "alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
        # - alertmanager:9093

scrape_configs:
- job_name: 'kafka'
  static_configs:
  - targets:
    - 'kafka-1:9999'
    - 'kafka-2:9999'
    - 'kafka-3:9999'

- job_name: 'consumer'
  static_configs:
  - targets:
    - 'consumer:8000'
  scrape_interval: 5s

- job_name: 'prometheus'
  static_configs:
  - targets:
    - 'localhost:9090'
