apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  namespace: kafka
  labels:
    app: kafka-consumer-fixed
spec:
  selector:
    app: kafka-consumer-fixed
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
