apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
  labels:
    app: kafka-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: kafka-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER_URL
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "posts"
        - name: KAFKA_DLQ_TOPIC
          value: "posts.dlq"
        - name: MAX_RETRIES
          value: "3"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - |
              import socket
              socket.socket().connect(('kafka-service', 9092))
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - |
              import socket
              socket.socket().connect(('kafka-service', 9092))
          initialDelaySeconds: 15
          periodSeconds: 5
