apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: kafka-producer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER_URL
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "posts"
        - name: MESSAGE_COUNT
          value: "0"
        - name: MESSAGE_INTERVAL
          value: "10.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - |
              import socket
              socket.socket().connect(('kafka-service', 9092))
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - |
              import socket
              socket.socket().connect(('kafka-service', 9092))
          initialDelaySeconds: 15
          periodSeconds: 5
